

#CREATE DATABASE
DROP DATABASE IF EXISTS goodviewer;
CREATE DATABASE goodviewer;
SELECT 'DATABASE goodviewer CREATED AND IN USE ' AS Msg;
USE goodviewer;



#CREATE TABLES
CREATE TABLE user (
Username VARCHAR(20) NOT NULL,
Age VARCHAR(20) NOT NULL,
Gender enum('Male','Female') NOT NULL,
Email VARCHAR(50) NOT NULL UNIQUE,
Password VARCHAR(20) NOT NULL,
CONSTRAINT PK_user PRIMARY KEY  (Username)
);

CREATE TABLE post (
PostID INT NOT NULL AUTO_INCREMENT,
Username VARCHAR(20) NOT NULL,
Subject VARCHAR(40) NOT NULL,
Content LONGTEXT NOT NULL,
Rate float(4) NOT NULL,
Image VARCHAR(400) NOT NULL,
Post_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT PK_post PRIMARY KEY  (PostID),
CONSTRAINT fk_user FOREIGN KEY(Username) REFERENCES user(Username)
);

CREATE TABLE reply (
ReplyID INT NOT NULL AUTO_INCREMENT,
Username VARCHAR(20) NOT NULL,
PostID INT NOT NULL,
Rsubject LONGTEXT NOT NULL,
Reply_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT PK_reply PRIMARY KEY  (ReplyID),
CONSTRAINT fk_user_reply FOREIGN KEY(Username) REFERENCES user(Username),
CONSTRAINT fk_post FOREIGN KEY(PostID) REFERENCES post(PostID)
);